# Generated by Django 4.1.3 on 2022-11-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=19)),
                ('weight', models.IntegerField(default=130)),
                ('blood_group', models.CharField(max_length=4)),
                ('last_donation', models.DateField(auto_now_add=True)),
                ('wants_to_donate', models.BooleanField(default=True)),
                ('needs_donation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Donation_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('donator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_history_set', to='core.client')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paitent_history_set', to='core.client')),
            ],
        ),
    ]
