# Generated by Django 4.1.3 on 2022-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bvn',
            field=models.IntegerField(default=19777393820),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default='sha234', max_length=128),
        ),
    ]
